name: IFCD

on:
  schedule:
    - cron: "30 18 * * *" 
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: wake-ifcd
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use secret token here
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/cyberpsychofc/Image-Feature-and-Corner-Detection.git
          git commit --allow-empty -m "Wake up signal for Streamlit"
          git push origin main
